# Generated by Django 4.2.2 on 2023-06-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_specialty_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.specialty'),
        ),
    ]
