# Generated by Django 4.2.2 on 2023-06-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_order_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('comment', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.order')),
            ],
        ),
    ]
