# Generated by Django 4.2.2 on 2023-06-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_order_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_report', to='users.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_order', to='users.order'),
        ),
    ]
